# Generated by Django 4.1 on 2022-09-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_item_categoria_allergene'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergene',
            name='categoria',
            field=models.CharField(blank=True, choices=[('l', 'Latticini'), ('g', 'Glutine'), ('a', 'Arachidi'), ('u', 'Uova')], default='', max_length=1),
        ),
    ]
