# Generated by Django 4.1 on 2022-09-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_allergene_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergene',
            old_name='categoria',
            new_name='tipo',
        ),
    ]
