# Generated by Django 4.1 on 2022-09-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_categoria_allergene_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Anonimo', max_length=100)),
                ('messaggio', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='snack',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='allergene',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Latticini', 'Latticini'), ('Glutine', 'Glutine'), ('Arachidi', 'Arachidi'), ('Uova', 'Uova'), ('Nichel', 'Nichel')], default='', max_length=30),
        ),
    ]
