# Generated by Django 4.1 on 2022-10-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_feedback_item_snack_alter_allergene_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='descrizione',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='nome',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
